name = "dweet-player"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[assets]
directory = "./src/static"

# Observability configuration
[observability.logs]
enabled = true
