name = "dweet-player"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Custom domain
routes = [
  { pattern = "dweetplayer.net", custom_domain = true }
]

# Static assets configuration
[assets]
directory = "./src/static"
not_found_handling = "single-page-application"

# Observability configuration
[observability.logs]
enabled = true
